export function buildVersionMatrix(input = {}) {
  const value = input && typeof input === 'object' ? input : {}
  return {
    generatedAt: value.generatedAt || new Date().toISOString(),
    pocVersion: value.pocVersion || 'unknown',
    nodeVersion: value.nodeVersion || process.version,
    dshVersion: value.dshVersion || null,
    cordisVersion: value.cordisVersion || null,
    reactVersion: value.reactVersion || null,
    ajvVersion: value.ajvVersion || null,
    playwrightVersion: value.playwrightVersion || null,
    storeVersion: value.storeVersion ?? null,
    storageDomain: value.storageDomain || null,
    tavernApiVersion: value.tavernApiVersion ?? null,
    browserScriptRuntime: value.browserScriptRuntime ?? null,
    hostPending: Array.isArray(value.hostPending) ? value.hostPending : [
      'Host-published official version matrix',
      'Tavern capabilities live version / browserScriptRuntime',
      'storageDomain canonical ownership / quota',
      'Unified diagnostics UI placement'
    ]
  }
}

export function renderVersionMatrixMarkdown(matrix) {
  const m = buildVersionMatrix(matrix)
  const row = (label, value) => `| ${label} | ${value === null || value === undefined || value === '' ? 'TBD' : value} |`
  return `# DSH Creative Suite — Host/Version Matrix\n\nGenerated: \`${m.generatedAt}\`\n\n## POC / Runtime\n\n| Item | Value |\n|---|---|\n${row('POC package', m.pocVersion)}\n${row('Node.js', m.nodeVersion)}\n${row('DSH CLI', m.dshVersion)}\n${row('cordis resolved', m.cordisVersion)}\n${row('React resolved', m.reactVersion)}\n${row('ajv resolved', m.ajvVersion)}\n${row('Playwright resolved', m.playwrightVersion)}\n${row('STORE_VERSION', m.storeVersion)}\n${row('storageDomain', m.storageDomain)}\n\n## Tavern Capabilities\n\n| Item | Value |\n|---|---|\n${row('Tavern gameplay API version', m.tavernApiVersion)}\n${row('browserScriptRuntime', m.browserScriptRuntime)}\n\n## Host Pending\n\n${m.hostPending.map(item => `- ${item}`).join('\n')}\n\n> This file is generated by \`dsh-creative-suite matrix\`. Host-side fields must be filled from the target host before publication.\n`
}
